/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ses;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;


import be.ses.CheckNeighboursInGrid;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        List<Integer> grid = Arrays.asList(0,0,1,0,1,1,0,2,2,0,1,3,0,1,1,1);
        System.out.println(CheckNeighboursInGrid.getSameNeighboursIds(grid, 4, 4, 5));
    }
}
